[package]
name = "w1729"
version = "0.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[dev-dependencies]
async-trait = "0.1"
cucumber = "0.13"
futures = "0.3"

[[test]]
name = "writers" # this should be the same as the filename of your test target
harness = false  # allows Cucumber to print output instead of libtest
