name: cucumber-tests
on: [pull_request]

jobs:
  check:
    name: Cucumber tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

#      - run: cargo update +nightly -Z minimal-versions

      - run: cargo check

      - run: cargo test
        env:
          RUSTFLAGS: -D warnings